"use client"
import React, { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./src/components/Footer/Footer";
import Header from "./src/components/Header/Header"

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [footerDelay, setFooterDelay] = useState(false);
  useEffect(() => {
    // Simulate loading time for demonstration purposes
    const timer = setTimeout(() => {
      setFooterDelay(true);
    }, 5000); // Adjust the delay time as needed

    // Clean up timer to prevent memory leaks
    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <head>
        <title>
          BotLab Dynamics | India&apos;s Leading Drone Show Company
        </title>

      </head>
      <body className={inter.className}>
        {/* <div className="fixed w-full sm:h-0 inset-0 h-screen z-[150]">
          <HeaderBar />
        </div> */}
        <Header />

        <main>{children}</main>

        <Footer />

      </body>
    </html>
  );
}
